#!/usr/bin/env bash
T='•••'
echo -e "\n                 40m    100m     41m    101m     42m    102m     43m    103m     44m    104m     45m    105m     46m    106m     47m    107m";
for FGs in '    m' '   1m' '  30m' '  90m' '  31m' '  91m' '  32m' \
           '  92m' '  33m' '  93m' '  34m' '  94m' '  35m' '  95m' \
           '  36m' '  96m' '  37m' '  97m';
  do FG=${FGs// /}
  echo -en " $FGs \033[$FG  $T  "
  for BG in 40m 100m 41m 101m 42m 102m 43m 103m 44m 104m 45m 105m 46m 106m 47m 107m;
    do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
  done
  echo;
done
echo
