#!/usr/bin/env bash

# Colors
export ESC_SEQ="\x1b["
export COL_RESET=$ESC_SEQ"39;49;00m"
export COL_RED=$ESC_SEQ"31;01m"
export COL_GREEN=$ESC_SEQ"32;01m"
export COL_YELLOW=$ESC_SEQ"33;01m"
export COL_BLUE=$ESC_SEQ"34;01m"
export COL_MAGENTA=$ESC_SEQ"35;01m"
export COL_CYAN=$ESC_SEQ"36;01m"
export COL_GREY=$ESC_SEQ"38;5;245m"

remotes=$(git remote | grep -vw 'origin')
if [ -z "${remotes}" ]; then
  echo -e "    ${COL_RED}No aditional remotes found!${COL_RESET}"
fi
for remote in ${remotes}; do
  read ahead behind <<< $(git rev-list --left-right --count origin/master...${remote}/master)
  echo -e "    ${COL_RESET}This fork is ${COL_YELLOW}${ahead}${COL_RESET} commits ahead and ${COL_RED}${behind}${COL_RESET} commits behind of Upstream."
done
