#!/usr/bin/env python

'''
Script to set the Kitty theme
This requires allow_remote_control yes in your kitty.conf
and the github.com/dexpota/kitty-themes repo to be checked out to ${HOME}/.kitty-themes
git clone https://github.com/dexpota/kitty-themes.git ${HOME}/.kitty-themes
'''

import os
import random
import subprocess
import sys

home = os.getenv("HOME")
kitty = f"{home}/.config/kitty"
choices_dir = f"{home}/.kitty-themes/themes"
choices = os.listdir(choices_dir)
dest = f"{kitty}/theme.conf"

if os.path.islink(dest):
    os.remove(dest)
new_theme = ""
if len(sys.argv) > 1:
    new_theme = sys.argv[1]
if new_theme == "":
    new_theme = random.choice(choices)
new_theme_path = f"{choices_dir}/{new_theme}"
os.symlink(new_theme_path, dest)

command = f"kitty @ set-colors -a -c {kitty}/kitty.conf"
subprocess.run(command, shell=True)

print(f"Kitty theme set to {new_theme}")
