#!/usr/bin/env bash
NAME='Luis Davim'
EMAIL='ldavim@ptc.com'

WORKINGCOPIES='${HOME}/workingCopies'
CODE='${HOME}/workingCopies/code'
GITHUB='${HOME}/workingCopies/code/github'
GITLAB='${HOME}/workingCopies/code/gitlab'
BITBUCKET='${HOME}/workingCopies/code/bitbucket'
DOCKERFILES='${HOME}/workingCopies/code/gitlab/dockerfiles'
TERRAFORM='${HOME}/workingCopies/code/bitbucket/tf_modules'
PLAYBOOKS='${HOME}/workingCopies/code/playbooks'
CHEF_ROLES='${HOME}/workingCopies/code/gitlab/chef/roles'
CHEF_ENVIRONMENTS='${HOME}/workingCopies/code/gitlab/chef/environments'
CHEF_HANDLERS='${HOME}/workingCopies/code/gitlab/chef/handlers'
CHEF_DATA_BAGS='${HOME}/workingCopies/code/gitlab/chef-data-bags'
CHEF_COOKBOOKS='${HOME}/workingCopies/code/gitlab/chef-cookbooks'
DCOS_CLUSTERS='${HOME}/workingCopies/code/bitbucket/dcos-clusrers'
