#!/usr/bin/env bash
NAME='Luis Davim'
EMAIL='luis.davim@jet.com'

WORKINGCOPIES='${HOME}/workingCopies'
CODE='${HOME}/workingCopies/src'
GITHUB='${HOME}/workingCopies/src/github.com'
GITLAB='${HOME}/workingCopies/src/gitlab.com'
BITBUCKET='${HOME}/workingCopies/src/bitbucket.org'
DOCKERFILES='${HOME}/workingCopies/src/gitlab.com/dockerfiles'
TERRAFORM='${HOME}/workingCopies/src/bitbucket.org/tf_modules'
PLAYBOOKS='${HOME}/workingCopies/src/playbooks'
CHEF_ROLES='${HOME}/workingCopies/src/gitlab.com/chef/roles'
CHEF_ENVIRONMENTS='${HOME}/workingCopies/src/gitlab.com/chef/environments'
CHEF_HANDLERS='${HOME}/workingCopies/src/gitlab.com/chef/handlers'
CHEF_DATA_BAGS='${HOME}/workingCopies/src/gitlab.com/chef-data-bags'
CHEF_COOKBOOKS='${HOME}/workingCopies/src/gitlab.com/chef-cookbooks'
DCOS_CLUSTERS='${HOME}/workingCopies/src/bitbucket.org/clusters/dcos-clusters'
