#!/bin/bash
sudo apt-add-repository "http://dl.bintray.com/aluxian/deb stable main"
sudo apt-add-repository "https://packagecloud.io/JonasGroeger/soundnode/ubuntu/ yakkety main"
sudo apt-add-repository "http://repository.spotify.com stable non-free"
sudo apt-add-repository "https://apt.dockerproject.org/repo ubuntu-yakkety testing"
sudo apt-add-repository "http://downloads.hipchat.com/linux/apt stable main"
sudo apt-add-repository "[arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
sudo apt-add-repository "https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client yakkety main"
sudo apt-add-repository "https://tel.red/repos/ubuntu yakkety non-free"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety main restricted"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety-updates main restricted"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety universe"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety-updates universe"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety multiverse"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety-updates multiverse"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety-backports main restricted universe multiverse"
sudo apt-add-repository "http://archive.canonical.com/ubuntu yakkety partner"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety-security main restricted"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety-security universe"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety-security multiverse"
sudo apt-add-repository "http://archive.ubuntu.com/ubuntu yakkety-proposed multiverse restricted main universe"
