#!/usr/bin/env bash
sudo apt-add-repository ppa:noobslab/themes
sudo apt-add-repository ppa:alexlarsson/flatpak
sudo apt-add-repository ppa:dawidd0811/neofetch
sudo apt-add-repository ppa:wereturtle/ppa
sudo apt-add-repository ppa:snwh/pulp
sudo apt-add-repository ppa:webupd8team/atom
sudo apt-add-repository ppa:fish-shell/release-2
sudo apt-add-repository ppa:atareao/atareao
sudo apt-add-repository ppa:linrunner/tlp
sudo apt-add-repository ppa:webupd8team/y-ppa-manager
sudo apt-add-repository ppa:libreoffice/ppa
sudo apt-add-repository ppa:team-xbmc/ppa
sudo apt-add-repository ppa:neovim-ppa/unstable
sudo apt-add-repository ppa:fixnix/indicator-systemtray-unity
sudo apt-add-repository ppa:apandada1/brightness-controller
sudo apt-add-repository ppa:fingerprint/fingerprint-gui
sudo apt-add-repository ppa:webupd8team/terminix
sudo apt-add-repository ppa:nathan-renniewaldock/flux
sudo apt-add-repository ppa:ultradvorka/ppa
sudo apt-add-repository ppa:nilarimogard/webupd8
sudo apt-add-repository ppa:pi-rho/dev
sudo add-apt-repository ppa:s.noack/ppa
sudo apt update
