# if [ -f "$HOME/.profile" ] && [ "$CONFIGURED" != "true" ]; then
if [ -f "$HOME/.profile" ] && ([[ ":$PATH:" != *":$HOME/.local/bin:"* ]] || [ "$CONFIGURED" != "true" ]); then
  . "$HOME/.profile"
fi
