# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

if [ "$CONFIGURED" == "true" ]; then
  exit 0
fi

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if [[ $(tty) == "/dev/tty"* ]] && [[ "$OSTYPE" == "linux-gnu" ]]; then
  setfont ter-powerline-v16b.psf.gz
fi

export EDITOR=vim
export VISUAL=vim
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  export TERMINAL=/usr/bin/gnome-terminal
fi

# CDPATH
export CDPATH='.:~:~/workingCopies:~/workingCopies/code:~/workingCopies/code/github:~/workingCopies/code/bitbucket:~/workingCopies/code/gitlab'

# GOPATH
export GOPATH="${HOME}/go"
export PATH="$PATH:$GOPATH/bin"

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
export HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=10000
export HISTFILESIZE=200000
export HISTTIMEFORMAT="%d-%m-%Y %H:%M:%S "

PROMPT_COMMAND="history -a; history -c; history -r; "'echo "$(history 1)" >> ~/.bash_eternal_history'";${PROMPT_COMMAND}"

# CTRL+R Alternatives

# Fuzzy Find

if [ -x "$(command -v fzf)" ]; then

__ehc() {
  if
    [[ -n $1 ]]
  then
    bind '"\er": redraw-current-line'
    bind '"\e^": magic-space'
    READLINE_LINE=${READLINE_LINE:+${READLINE_LINE:0:READLINE_POINT}}${1}${READLINE_LINE:+${READLINE_LINE:READLINE_POINT}}
    READLINE_POINT=$(( READLINE_POINT + ${#1} ))
  else
    bind '"\er":'
    bind '"\e^":'
  fi
}

__fzf_history ()
{
  __ehc $(history | fzf --tac --tiebreak=index --height=10 | perl -ne 'm/^\s*([0-9]+)/ and print "!$1"')
}

bind '"\C-r": "\C-x1\e^\er"'
bind -x '"\C-x1": __fzf_history';

# HH

elif [ -x "$(command -v hh)" ]; then

  # hh configuration:
  # https://github.com/dvorka/hstr
  # Generated with: hh --show-configuration >> ~/.bashrc
  export HH_CONFIG=hicolor         # get more colors
  # export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"   # mem/file sync
  # if this is interactive shell, then bind hh to Ctrl-r (for Vi mode check doc)
  if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hh -- \C-j"'; fi

fi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# Ubuntu’s command-not-found equivalent for Homebrew on OSX
if [[ "$OSTYPE" == "darwin"* ]]; then
  if brew command command-not-found-init > /dev/null 2>&1; then eval "$(brew command-not-found-init)"; fi
fi

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# colored less
export LESS='-R'

# Key bindings, up/down arrow searches through history
bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward
bind '"\C-\e[B"':"\"\C-k\C-ahistory | grep '^ *[0-9]* *\C-e.'\C-m\""
bind Space:magic-space

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  # export RBENV_ROOT="$(brew --prefix rbenv)"
  # export GEM_HOME="$(brew --prefix)/opt/gems"
  # export GEM_PATH="$(brew --prefix)/opt/gems"
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
  fi
fi

if [ -x "$(command -v aws_completer)" ]; then
  complete -C 'aws_completer' aws
fi

if [ -x "$(command -v awless)" ]; then
  if [ -f ~/.bash/awless.completion.sh ]; then
    source ~/.bash/awless.completion.sh
  else
    awless completion bash >> ~/.bash/awless.completion.sh
    source ~/.bash/awless.completion.sh
  fi
fi

# if [ -x "$(command -v azure)" ]; then
#   if [ -f ~/.bash/azure.completion.sh ]; then
#     source  ~/.bash/azure.completion.sh
#   else
#     azure --completion >> ~/.bash/azure.completion.sh
#     source  ~/.bash/azure.completion.sh
#   fi
# fi

if [ -x "$(command -v kontena)" ]; then
  source "$(kontena whoami --bash-completion-path)"
fi

if [ -x "$(command -v pyenv)" ]; then
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
fi

if [ -x "$(command -v thefuck)" ]; then
 eval $(thefuck --alias)
fi

if [ -x ~/.chefvm/bin/chefvm ]; then
  eval "$(~/.chefvm/bin/chefvm init -)"
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  source /etc/profile.d/vte-2.91.sh
fi

[ -f ~/.kube-fzf/kube-fzf.sh ] && source ~/.kube-fzf/kube-fzf.sh

# gitprompt configuration

# bash-git-prompt configuration - https://github.com/magicmonty/bash-git-prompt:
# GIT_PROMPT_ONLY_IN_REPO=1
# GIT_PROMPT_FETCH_REMOTE_STATUS=0   # uncomment to avoid fetching remote status
# GIT_PROMPT_SHOW_UPSTREAM=1 # uncomment to show upstream tracking branch
# GIT_PROMPT_STATUS_COMMAND=gitstatus_pre-1.7.10.sh # uncomment to support Git older than 1.7.10
# GIT_PROMPT_START=...    # uncomment for custom prompt start sequence
# GIT_PROMPT_END=...      # uncomment for custom prompt end sequence
GIT_PROMPT_THEME=Custom # use custom .git-prompt-colors.sh
# GIT_PROMPT_THEME=Solarized # use theme optimized for solarized color scheme
# GIT_PROMPT_THEME=Single_line_Ubuntu
source ~/.bash/bash-git-prompt/gitprompt.sh

# source ~/.bash/git_prompt.sh

# Promptline - https://github.com/edkolev/promptline.vim
# source ~/.bash/shell_prompt.sh

# Powerline-shell - https://github.com/milkbikis/powerline-shell
# function _update_ps1() {
#     PS1="$(~/.bash/powerline-shell/powerline-shell.py $? 2> /dev/null)"
# }
#
# if [ "$TERM" != "linux" ]; then
#     PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
# fi

CONFIGURED="true"

if command -v tmux>/dev/null; then
    [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi

if [[ -f $HOME/.bash_variables ]]; then
  source $HOME/.bash_variables
fi

