#!/bin/sh

INSTANCE="${1:-BAT0}"
ALERT_LOW="${2:-10}"

if test -e "/sys/class/power_supply/$INSTANCE"
then
  status=$(cat /sys/class/power_supply/$INSTANCE/status)
  capacity=$(cat /sys/class/power_supply/$INSTANCE/capacity)
  case "$status" in
    "Discharging")
      symbol=''
      remaining="$(upower -i /org/freedesktop/UPower/devices/battery_$INSTANCE | grep -E "time" | cut -d ' ' -f 14-15)"
      #remaining="$(acpi)"
      ;;
    "Charging")
      symbol=''
      remaining="$(upower -i /org/freedesktop/UPower/devices/battery_$INSTANCE | grep -E "time" | cut -d ' ' -f 15-16)"
      #remaining="$(acpi)"
      ;;
    "Full")
      exit
      ;;
  esac
  if [ $capacity -gt 89 ]
  then
    baticon=''
  else
    if [ $capacity -gt 62 ]
    then
      baticon=''
    else
      if [ $capacity -gt 35 ]
      then
        baticon=''
      else
        if [ $capacity -gt 10 ]
        then
          baticon=''
        else
          baticon=''
        fi
      fi
    fi
  fi

  # if [ "$remaining" != "" ]; then
  #   remaining="[$remaining]"
  # fi

  # Full text
  echo "$baticon $capacity% $remaining"
  # Short text
  echo "$baticon $capacity% $symbol"

  # Color
  color=''
  if test $capacity -le $ALERT_LOW -a $status = "Discharging"
  then
  color="#FF0000"
  fi
  if test $capacity -le 100 -a $status = "Charging"
  then
  color="#00FF00"
  fi
  echo "${color}"
fi
