#!/bin/bash

DEVICE="${BLOCK_INSTANCE:-intel_backlight}"
BRIGHTNESS_PATH="/sys/class/backlight/$DEVICE/brightness"
MAXBRIGHTNESS=$(cat /sys/class/backlight/$DEVICE/max_brightness)
MINBRIGHTNESS=1
light=$(cat $BRIGHTNESS_PATH)

function brightness() {
  NUMBER=$1
  #Check if integer
  Int='^[0-9]+$'
  if [[ $NUMBER =~ $Int ]]; then
    if [[ $NUMBER -ge $MAXBRIGHTNESS ]]; then
      NUMBER=$MAXBRIGHTNESS
    elif [[ $NUMBER -lt $MINBRIGHTNESS ]]; then
      NUMBER=$MINBRIGHTNESS
    fi
    echo $NUMBER > $BRIGHTNESS_PATH
  fi
}

# [ $# -eq 1 ] && brightness $(($light - $1))

case $BLOCK_BUTTON in
# Left click
  1) brightness $(($light + 100)) ;;
# Middle click
  2) brightness $MAXBRIGHTNESS ;;
# Right click
  3) brightness $(($light - 100)) ;;
esac

light=$(($(($light*100))/$MAXBRIGHTNESS))
echo " $light% "
