#!/bin/bash

player_status="$(mpc | grep -oE '(playing|pause)')"

echo -n '<span foreground="#d33682">« </span>'

widget() {
  if [[ "$player_status" == 'playing' ]]; then
    format='<span foreground="##b58900">'
    format="$format%title%"
    format="$format</span>"
    format="$format<span foreground='##586e75'> <i>by</i> </span>"
    format="$format<span foreground='##cb4b16'>"
    format="$format%artist%"
    format="$format</span>"

    now_playing=$(mpc -f "$format" | head -1)

    echo -n $now_playing
  else
    echo -n 'mpd <span foreground="#586e75"><i>paused</i></span>'
  fi
}

case $BLOCK_BUTTON in
    3) mpc toggle && widget ;;  # right click, pause/unpause
    4) mpc prev   && widget ;;  # scroll up, previous
    5) mpc next   && widget ;;  # scroll down, next
    *) widget ;;
esac
