#!/usr/bin/env bash
# vim:ts=4:sw=4:expandtab
OUTPUT=$(sensors -Au)
# IFS=$'\n'
NCORES=$(sensors -Au | grep -c "Core")
CURRENT=""
HIGH=""
icon=' '

for i in $(seq 0 $(($NCORES -1))); do
  CORE="Core $i"
  DATA=$(echo "${OUTPUT}" | egrep -A4 "${CORE}")
  CURRENT="$(echo "${DATA}" | grep -Po "(?<=_input: )([0-9]+)") $CURRENT"
  HIGH="$(echo "${DATA}" | grep -Po "(?<=_max: )([0-9]+)") $HIGH"
  #CRIT=$(echo "${DATA}" | grep -Po "(?<=_crit: )([0-9]+)")
done

# HIGH=$(echo $HIGH | sed -e 's/\s*$//g')
HIGH=($HIGH)
# CURRENT=$(echo $CURRENT | sed -e 's/\s*$//g')
CURRENT=($CURRENT)

echo " ${icon} ${CURRENT[@]} "
#[[ "${CURRENT[0]}" -lt 50 ]] && echo ''&& echo "#808080"

[[ "${CURRENT[0]}" -gt "${HIGH[0]}" ]] && exit 33
exit 0
