#!/bin/sh

if [ -e '/usr/bin/synclient' ]
then
  enable=$(synclient -l | grep -c 'TouchpadOff.*=.*0')

  if [ $enable -eq 1 ]; then
    echo '[ ]'
    echo ''
    echo '#00FF00'
  else
    echo '[X]'
    echo ''
    echo '#FF0000'
  fi
fi
