#!/usr/bin/env zsh

if [[ "$CONFIGURED" == "true" ]]; then
  return
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="spaceship"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data
setopt hist_ignore_space      # ignore commands that start with space
setopt append_history         # append rather then overwrite
setopt extended_history       # save timestamp
setopt inc_append_history     # add history immediately after typing a command
setopt hist_reduce_blanks     # remove superfluous blanks

_eternal_history_histfile=~/.zsh_eternal_history

_eternal_history_mark_for_save() {
  __eternal_history_command_entered=true
}

_eternal_history_save() {
  if $__eternal_history_command_entered; then
    echo $$ $USER "$(fc -liD -1)" >> $_eternal_history_histfile
  fi
  __eternal_history_command_entered=false
}

autoload -U add-zsh-hook
add-zsh-hook preexec _eternal_history_mark_for_save
add-zsh-hook precmd _eternal_history_save

hgrep() {
  if [ ! -z "$1" ]; then
    grep "${1}" $_eternal_history_histfile
  else
    history
  fi
}
alias histg='hgrep'

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Tmux plugin config
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOSTART_ONCE=true
export ZSH_TMUX_AUTOQUIT=true
export ZSH_TMUX_AUTOCONNECT=false

export GIT_AUTO_FETCH_INTERVAL=60 #in seconds

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  history
  ssh-agent
  git
  git-auto-fetch
  tmux
  thefuck
  kube-ps1
  colorize
  colored-man-pages
  command-not-found
  cp
  extract
  zsh-syntax-highlighting
  zsh-autopair
  zsh-completions
  zsh-autosuggestions
  zsh-history-substring-search
)

# Bash like CDPATH
typeset -U path cdpath fpath
setopt auto_cd autocd

zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format %d
zstyle ':completion:*:descriptions' format %B%d%b
zstyle ':completion:*:complete:(cd|pushd):*' tag-order \
        'local-directories named-directories'

# Brew completions
# You may also need to forcibly rebuild zcompdump:
# rm -f ~/.zcompdump; compinit
# Additionally, if you receive “zsh compinit: insecure directories” warnings when attempting to load these completions,
# you may need to run this:
# chmod -R go-w "$(brew --prefix)/share"
if [ -x "$(command -v brew)" ]; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  FPATH=${HOMEBREW_PREFIX}/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

if [[ "$OSTYPE" == "darwin"* ]]; then
    MAX_MEMORY_UNITS=KB
else
    MAX_MEMORY_UNITS=MB
fi

export TIMEFMT='%J   %U  user %S system %P cpu %*E total'$'\n'\
'avg shared (code):         %X KB'$'\n'\
'avg unshared (data/stack): %D KB'$'\n'\
'total (sum):               %K KB'$'\n'\
'max memory:                %M '$MAX_MEMORY_UNITS''$'\n'\
'page faults from disk:     %F'$'\n'\
'other page faults:         %R'

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#

alias -s {yml,yaml,json}=$EDITOR

# eval "$(starship init zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

if [[ -f ~/.profile ]]; then
  source ~/.profile
  export $(grep '^[ a-zA-Z0-9]*=' ~/.profile | tr -d '[:blank:]' | cut -d= -f1 | sort -u)
fi

[[ ! -f ~/.aliases ]] || source ~/.aliases
[[ ! -f /etc/grc.zsh ]] || source /etc/grc.zsh
[[ ! -f /usr/local/etc/grc.zsh ]] || source /usr/local/etc/grc.zsh
[[ ! -f /usr/local/opt/fzf/shell/key-bindings.zsh ]] || source /usr/local/opt/fzf/shell/key-bindings.zsh

[[ ! -f $HOME/.kbenv/kbenv.sh ]] || source $HOME/.kbenv/kbenv.sh
[[ ! -f $HOME/.helmenv/helmenv.sh ]] || source $HOME/.helmenv/helmenv.sh
[[ ! -f ${HOME}/.ktx ]] || source ${HOME}/.ktx/ktx

export CONFIGURED="true"
